### PR TITLE
Customisable greeting

### PR DESCRIPTION
**Pull request by odarriba**
This PR adds the ability to customise greeting from config (so easily changed using system env vars or whatever).

### CODE REVIEW

**Comment by gravityblast** [comment]
LGTM

**Comment by devansjo** [comment]
LGTM but ask Hardy or Janel to review copy?

**Comment by gravityblast** [comment]
yes, we need to ask them for the final copy but I'm going to merge it in the meantime so that I can tests config vars in heroku

**Comment by odarriba** [comment]
@pilu maybe we can use imports of config like in phoenix apps, using mix environment to load one file or another

**Comment by gravityblast** [comment]
yeah we can do that too!
for now I'm just getting the GREETING env var so that I can customise it on heroku without changing the code

**Comment by zimakki** [comment]
I writing the first greeting message now. @pilu wait till you have it from me before pushing out the first notification. :)

**Pull request merged**
